// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4iNjcb390KJOi25VaGVsTCM1djA4zXD8',
    appId: '1:104141305158:web:16755bef131a8c2acba147',
    messagingSenderId: '104141305158',
    projectId: 'hobbio-6b939',
    authDomain: 'hobbio-6b939.firebaseapp.com',
    storageBucket: 'hobbio-6b939.appspot.com',
    measurementId: 'G-M176GP825J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZfsXWpB5oIH3wrC0iWLeMIgYnHpe6-Pg',
    appId: '1:104141305158:android:847d532cee235b87cba147',
    messagingSenderId: '104141305158',
    projectId: 'hobbio-6b939',
    storageBucket: 'hobbio-6b939.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWS6gvS2R8Tfmf6fIUhlDIbBR8HC7M2c',
    appId: '1:104141305158:ios:f1364fbf32d8cac1cba147',
    messagingSenderId: '104141305158',
    projectId: 'hobbio-6b939',
    storageBucket: 'hobbio-6b939.appspot.com',
    iosBundleId: 'com.example.flutterForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWS6gvS2R8Tfmf6fIUhlDIbBR8HC7M2c',
    appId: '1:104141305158:ios:861afa14884b5b19cba147',
    messagingSenderId: '104141305158',
    projectId: 'hobbio-6b939',
    storageBucket: 'hobbio-6b939.appspot.com',
    iosBundleId: 'com.example.flutterForm.RunnerTests',
  );
}
